# Generated by Django 5.1.6 on 2025-06-11 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المشترك')),
                ('duration', models.IntegerField(default=30, verbose_name='مدة الاشتراك المطلوبة (بالأيام)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بدء الاشتراك')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الاشتراك')),
                ('status', models.CharField(choices=[('pending', 'في انتظار الموافقة'), ('active', 'نشط'), ('expired', 'منتهي')], default='pending', max_length=10, verbose_name='حالة الاشتراك')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
        ),
    ]
