# Generated by Django 5.1.6 on 2025-06-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المشترك')),
                ('start_date', models.DateField(verbose_name='تاريخ بدء الاشتراك')),
                ('end_date', models.DateField(verbose_name='تاريخ انتهاء الاشتراك')),
            ],
        ),
    ]
